trailingComma: "es5"
semi: false
singleQuote: false
jsxSingleQuote: false
printWidth: 160
tabWidth: 4
overrides:
  - files: "package.json"
    options:
      tabWidth: 2
  - files: "*.yml"
    options:
      tabWidth: 2
